type Contact {
  fullName: String!
}

type Seed {
  slug: String
  name: String
  description: String
  contact: Contact
}

type Query {
  seed(slug: String!): Seed
  seeds(skip: Int, take: Int): [Seed]!
}
